<section id="aviso_privacidad">
<h1 class="stAv">TÉRMINOS Y CONDICIONES DE USO</h1>
<h2 class="apriv">Estimado Usuario:</h2>
<p class="apriv">Este contrato describe los términos y condiciones generales (en adelante los "Términos y Condiciones Generales") que se aplican por el uso de los servicios que ofrece Pasaje de Electrónica el Salvador S.A. de C.V. (en adelante "los Servicios") dentro del sitio de internet www.plazadelatecnologia.com.mx (en adelante el "Sitio"). Pasaje de Electrónica el Salvador y el Sitio serán referidos en el texto de estos Términos y Condiciones Generales, indistintamente, como Plaza de la Tecnología. Cualquier persona que desee acceder y/o usar el sitio o los servicios lo hace sujetándose a los Términos y Condiciones Generales, junto con todas las demás políticas y principios que rigen a Plaza de la Tecnología.<br>
Cualquier persona que no acepte los términos y condiciones generales de Plaza de la Tecnología, los cuales tienen carácter obligatorio, no podrá utilizar el sitio y/o los servicios que ofrece.<br>
Previos a su inscripción como Usuario de Plaza de la Tecnología, el Usuario del sitio debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en el Aviso de Privacidad así como en los demás documentos incorporados a los mismos por referencia.<br></p>
<br />  
<h2 class="apriv">De la Capacidad</h2>
<p class="apriv">Los Servicios sólo están disponibles para personas que tengan capacidad legal para contratar. No podrán utilizar los servicios las personas que no tengan esa capacidad, los menores de edad o Usuarios de Plaza de la Tecnología que por algún motivo hayan sido suspendidos temporalmente o inhabilitados definitivamente. Si estás inscribiendo un Usuario como Empresa, debes tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este Acuerdo.</p>
<br />
<h2 class="apriv">Inscripción de los Usuarios</h2>
<p class="apriv">Para poder utilizar los servicios que brinda Plaza de la Tecnología es obligatorio completar el formulario de inscripción en todos sus campos con datos válidos y verdaderos. El que se inscribe como Usuario deberá completarlo con su información personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los Datos Personales. Plaza de la Tecnología NO se responsabiliza por la certeza y veracidad de los Datos Personales proporcionados por los Usuarios, siendo ésta información responsabilidad exclusiva de los mismos. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de sus Datos Personales ingresados.<br>
Plaza de la Tecnología se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, así como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En los casos de inhabilitación, se dará de baja todos los artículos publicados sin responsabilidad para Plaza de la Tecnología.<br>
El Usuario accederá a su cuenta personal (en adelante "Cuenta") mediante el ingreso de su Nombre o Nickname y contraseña de seguridad elegida personalmente ("Clave de Seguridad"). El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad siendo de su responsabilidad total la utilización de ésta, por lo que el Usuario será responsable por todas las operaciones efectuadas en su Cuenta y a su nombre, pues el acceso a la misma está restringido al ingreso de su Clave de Seguridad, la cual es de conocimiento exclusivo del Usuario.<br>
Plaza de la Tecnología  se reserva el derecho de rechazar cualquier solicitud de inscripción o de cancelar una inscripción previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.</p>
<br />
<h2 class="apriv">De las Modificaciones a los Términos y Condiciones</h2>
<p class="apriv">Plaza de la Tecnología puede modificar los Términos y Condiciones Generales en cualquier momento y deberá publicar dichos cambios en el Sitio. Todos los términos modificados entrarán en vigor a los 5 (cinco) días de su publicación. Dentro de los 3 (tres) días siguientes a la publicación de las modificaciones, el Usuario deberá comunicar por e-mail si no acepta las mismas; en ese caso queda disuelto el vínculo contractual y será inhabilitado como Usuario siempre que no tenga deudas pendientes. Vencido este plazo, se considerará que el Usuario acepta los nuevos términos y el contrato continuará vinculando a ambas partes y con los nuevos términos.</p>
<br />
<h2 class="apriv">De los Bienes que se Venden y Compran</h2>
<p class="apriv">Los usuarios se dividen en Vendedores (en adelante “Usuario Vendedor”) que son los Usuarios que mediante compraventa enajenan un producto de los exhibidos en el sitio por los Usuarios Vendedores, y los Compradores (en adelante “Usuario Comprador”) que son los Usuarios que mediante compraventa adquieren los producto exhibidos en el sitio por los Usuarios Vendedores. Cuando se utilice el término “Usuarios” se entiende que se habla de los Usuarios Vendedores y Compradores al mismo tiempo.
Utilización de PayPal y Dinero Mail. Al publicar un producto en el Sitio, el usuario vendedor consiente expresamente la utilización de PayPal y Dinero Mail como una de las formas disponibles para el pago del bien o servicio ofrecido. Asimismo, el usuario declara que ha leído, comprendido y aceptado los Términos y Condiciones de Uso de utilización de dichos servicios y que se pueden consultar en los siguientes sitios de internet:<br>
<a title="Paypal" href="https://cms.paypal.com/mx/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full" target="_blank">Paypal</a><br>
<a title="Dinero Mail" href="https://mx.dineromail.com/terminos-y-condiciones" target="_blank">Dinero Mail</a> (GENERALES) *Ver Anexo 1<br>
Publicación de bienes y/o servicios. El Usuario Vendedor debe ofertar los bienes y/o servicios en las categorías y subcategorías apropiadas. Las publicaciones pueden incluir textos descriptivos, gráficos, fotografías y otros contenidos y condiciones pertinentes para la venta del bien o la contratación del servicio, siempre que no violen ninguna disposición de este acuerdo o demás políticas de Plaza de la Tecnología, así como cualquier disposición legal mexicana o acuerdo internacional, de lo contrario Plaza de la Tecnología se reserva el derecho de dar de baja dicho producto o servicio.  El producto ofrecido por el Usuario Vendedor debe ser exactamente descrito en cuanto a sus condiciones y características relevantes. Se entiende  que mediante la inclusión del bien o servicio en Plaza de la Tecnología, el Usuario Vendedor tiene disponible para su entrega inmediata.<br> 
El Usuario Vendedor debe publicar los productos expresados en pesos mexicanos y con IVA incluido cuando corresponda la aplicación del mismo. Plaza de la Tecnologia podrá remover cualquier publicación cuyo precio no sea expresado de esta forma para evitar confusiones o malos entendidos en cuanto al precio final del producto.<br>
En caso que se infrinja cualquiera de las disposiciones establecidas en esta cláusula, Plaza de la Tecnología podrá editar el espacio, solicitar al Usuario que lo edite, o dar de baja la publicación donde se encuentre la infracción.<br>
Inclusión de imágenes y fotografías. El usuario puede incluir imágenes y fotografías del producto ofrecido siempre que las mismas correspondan con el artículo que se pretende vender, salvo que se trate de bienes o productos o de servicios que por su naturaleza no permiten esa correspondencia o se especifique claramente en la publicación del artículo.</p>
<br />
<h2 class="apriv">De la Privacidad de la Información</h2>
<p class="apriv">Los Usuarios deberán facilitar determinados datos de carácter personal al momento de crear su cuenta en Plaza de la Tecnología. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica. Para mayor información sobre la privacidad de los Datos Personales y casos en los que será revelada la información personal, se pueden consultar nuestro <a title="Aviso de Privacidad" href="<?=base_url();?>avisoPrivacidad" target="_blank">Aviso de Privacidad</a>.</p>
<br />
<h2 class="apriv">De las Obligaciones de los Usuarios</h2>
<p class="apriv">Obligaciones del Usuario Comprador. Durante el plazo fijado por el Usuario Vendedor, los Usuarios Compradores  interesados realizarán ofertas de compra para los bienes y ofertas de contratación para los servicios. La oferta de venta se cierra una vez que vence el plazo o se acaban las cantidades estipuladas por el Usuario Vendedor, y la oferta de contratación del servicio culmina con el vencimiento del plazo de la publicación.<br>
Al ofertar por un artículo el Usuario Comprador acepta quedar obligado por las condiciones de venta incluidas en la descripción del artículo.<br>
Obligaciones del Usuario Vendedor. El Usuario Vendedor debe tener capacidad legal para vender el bien objeto de su oferta.<br>
Dado que Plaza de la Tecnología es un punto de encuentro entre los Usuarios compradores y vendedores, Plaza de la Tecnología no participa de las operaciones que se realizan entre ellos, el Usuario Vendedor será responsable por todas las obligaciones y cargas que correspondan por la venta de sus artículos, sin que pudiera imputársele a Plaza de la Tecnología algún tipo de responsabilidad por incumplimientos en ese sentido.<br>
Plaza de la Tecnología sólo pone a disposición de los Usuarios un espacio en internet que les permite tener comunicación para vender o comprar artículos y/o servicios.</p>
<br />
<h2 class="apriv">De las Sanciones. Suspensión de operaciones</h2>
<p class="apriv">Plaza de la Tecnología puede suspender en forma temporal o inhabilitar definitivamente la Cuenta de un Usuario o su publicación, si se viola alguna ley, o los presentes Términos y Condiciones Generales; si se incurriera a criterio de Plaza de la Tecnología en posibles actos fraudulentos; si no pudiera verificarse la identidad del Usuario o cualquier información proporcionada por el mismo fuere errónea. En caso de suspensión o inhabilitación de un Usuario, todos los artículos que tuviera publicados serán removidos del sitio.</p>
<br />
<h2 class="apriv">De la Responsabilidad</h2>
<p class="apriv">Plaza de la Tecnología no es el propietario de los artículos publicados en el sitio por los Usuarios Vendedores para su venta y tampoco tiene posesión de los mismos. Plaza de la Tecnología no intervienen ningún sentido ni responsabilidad en la compraventa  de los productos realizada entre los Usuarios, tampoco en la oferta de la prestación de servicios que se obliga a dar el Usuario Vendedor, por lo que no es responsable ante cualquier circunstancia que se pudiera dar en virtud de las negociaciones entre Usuarios. Cada Usuario es responsable por los artículos que publica para su venta y por las compras que realiza. Tampoco será responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de la operación. El Usuario conoce y acepta que al realizar operaciones con otros Usuarios o terceros lo hace bajo su propio riesgo. No será responsable por cualquier daño y/o perjuicio que sufra el Usuario en virtud de las operaciones realizadas o no realizadas</p>
<br />
<h2 class="apriv">De las Fallas en el Sistema</h2>
<p class="apriv">Plaza de la Tecnología no es responsable por daño, perjuicio o pérdida causados al Usuario por alguna falla en el sistema, en el servidor o en Internet. Plaza de la Tecnología no garantiza el acceso y uso continuo e ininterrumpido de su sitio debido a que esta fuera de su alcance. El sistema puede eventualmente no estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otra circunstancia ajena a Plaza de la Tecnología; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad.</p>
<br />
<h2 class="apriv">De las Tarifas</h2>
<p class="apriv">La inscripción en Plaza de la Tecnología es totalmente gratuita para usuarios y locatarios. Es de  uso exclusivo de los locatarios la venta de sus productos en www.plazadelatecnologia.com. Este beneficio es adicional a la renta de un local dentro de cada una de sus plazas y de venta extensiva para quién decide utilizar la plataforma de venta en línea.<br> 
Todos los productos que están a la venta en Plaza de la Tecnología tienen una comisión adicional al precio por pieza de un 8%, precio por uso de la plataforma de transacción bancaria de nuestros proveedores.<br>
Plaza de la Tecnología se reserva el derecho de modificar, cambiar, agregar, o eliminar las comisiones vigentes, en cualquier momento, situación que será notificada a los Usuarios, en la forma establecida en la Cláusula 3.<br>
Plaza de la Tecnología se reserva el derecho de tomar las medidas legales que estime pertinentes para obtener el pago del monto debido.</p>
<br />
<h2 class="apriv">Anexo 1</h2>
<p class="apriv">1. - El uso del servicio de Dinero Mail (en adelante  el “SISTEMA”)  implica la aceptación tácita sin reservas por parte del USUARIO del presente Contrato  y todo documento al cual se hace referencia en el sitio de internet https://mx.dineromail.com/Index (en adelante el “SITIO”)<br>
2. - El SISTEMA podrá estar disponible y podrá ser usado por cualquier persona que tenga capacidad legal. Sin embargo para el caso de compradores que sean menores de edad y que utilicen tarjetas de crédito/débito o para aquellos incapaces legalmente para contratar, el SISTEMA no estará disponible.<br>
3. - Toda la información que el USUARIO provea en el registro de el SISTEMA debe ser verdadera. Si luego del registro, alguno de los datos provistos cambia, el USUARIO debe prontamente actualizar la información de su cuenta. La provisión de información falsa o desactualizada puede ocasionar el cierre de la “Cuenta” del USUARIO. Aunque Dinero Mail (en adelante la “EMPRESA”) no está obligado a monitorear la veracidad de la información provista, el USUARIO acepta el derecho de corroborar que los datos otorgados son correctos, en forma manual o automatizada.<br> 
Asimismo, las partes acuerdan proteger de conformidad con lo establecido por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP), los datos personales de los USUARIOS así como de cualquier tercero que llegue a tratarse a través del SISTEMA atendiendo a lo establecido en el Aviso de Privacidad publicado en el sitio URL: https://mx.dineromail.com/Index 13<br> 
EL USUARIO manifiesta que ha puesto previamente a la celebración del presente contrato, el Aviso de Privacidad a disposición de los titulares de los datos personales que ingresen al SISTEMA, mediante el cual ha obtenido el consentimiento para tratar dichos datos personales para esta finalidad, prevista en dicho Aviso.<br> 
Las partes acuerdan que la EMPRESA, en su carácter de Encargado, única y exclusivamente tratará los datos ingresados al SISTEMA conforme a las instrucciones de EL USUARIO y únicamente los utilizará o aplicará para prestar los servicios objeto de este Contrato.<br>
En ningún caso la EMPRESA tratará los datos contenidos en el SISTEMA para finalidades distintas de las establecidas en el presente Contrato, ni los transferirá a favor de terceras personas, salvo en los casos que resulte necesario para cumplir con lo estipulado en el presente contrato.<br> 
Las partes acuerdan que a la terminación por cualquier causa del presente contrato, LA EMPRESA deberá cancelar o suprimir los datos personales del SISTEMA obtenidos durante la vigencia del presente contrato, salvo en los casos que requieran ser conservados en atención a las disposiciones aplicables a la ley de la materia de que se trate.<br> 
4.- El SISTEMA utiliza tecnología cookie y de rastreo de IP cuando un USUARIO navega por el SITIO, que permiten reconocer a aquellos que están registrados sin que tengan que ingresar su e-mail cada vez que acceden al SITIO y recopila cierta información de sus sistemas, preferencias y operaciones. El rechazo de los cookies enviados por el  SISTEMA por parte del USUARIO puede afectar el correcto funcionamiento del SITIO. En caso de permitir la utilización de esta tecnología, el USUARIO consiente que la información personal así obtenida sea utilizada para analizar sus preferencias, para definir y ejecutar políticas de mercadeo personalizadas y para otras aplicaciones vinculadas al SITIO.<br>
5.- La EMPRESA no cobrará anualidades, mensualidades o restringirá la cantidad de operaciones por parte de sus USUARIOS que hagan uso del SISTEMA.<br> 
6.-  Al abrir una cuenta en el SISTEMA por los USUARIOS esta no tendrá:<br> 

Tiempo limitado de uso.<br>
Cantidad limitada de Actos de comercio.<br> 
Número de operaciones por comprador.<br>
Suspensión por inactividad de la cuenta.<br> 

7.- El SISTEMA permite al USUARIO realizar compras por internet así como solicitar por parte del VENDEDOR la solicitud de transferencia de fondos de su cuenta registrada.<br> 
8.- Las Cuentas de Dinero Mail están denominadas en "Pesos Mexicanos" y todas las referencias a dinero en el SISTEMA se entienden realizadas en esa moneda de curso legal en la República Mexicana, a excepción de aquellas en las que expresamente se indique lo contrario, sin embargo aunque el USUARIO en su carácter de VENDEDOR pueda realizar cotizaciones en dólares estadounidenses en su SITIO de internet y en el SISTEMA sea expresado así, dichas operaciones al momento de procesarlas se verán reflejadas en pesos mexicanos al tipo de cambio actual.<br> 
9.- Al efectuar cualquier operación que implique un débito de fondos de la Cuenta de Dinero Mail solicitada por el USUARIO en su calidad de vendedor, éste autoriza a la EMPRESA a utilizar el monto correspondiente en la “Cuenta Recaudadora”. <br>
10.- Los fondos acreditados en la “Cuenta Recaudadora” de la EMPRESA producto de las ventas de bienes y/o servicios no generan intereses que beneficien o perjudiquen al USUARIO vendedor.<br>
11.- Las INSTRUCCIONES DE PAGO son hechas por los USUARIOS y son resultado de la venta de bienes y/o servicios.<br>
12.- Las instrucciones de pago ("operaciones") sólo se efectúan en el SITIO a través del botón de compra generado por el SISTEMA. No son válidas las instrucciones cursadas por teléfono, fax, correo electrónico o cualquier otro medio ajeno al SISTEMA.<br> 
13.- LA EMPRESA solo aceptará pagos en los que medie una instrucción expresa hecha a través del SISTEMA pudiendo el USUARIO en su calidad de vendedor utilizar diferentes esquemas de negocios autorizados por la EMPRESA para operar. De igual manera la EMPRESA aceptará pagos de USUARIOS registrados en Dinero Mail los cuales deberán utilizar su e-mail y su clave personal secreta para ingresar al SISTEMA.<br> 
14.- Desde el momento en que se inicia una instrucción de pago por parte del usuario comprador y hasta el momento en que el SISTEMA como receptor de los fondos acepta la operación, el USUARIO en su calidad de vendedor es el único dueño de los fondos utilizados, y la EMPRESA mantiene esos fondos únicamente como su agente de pago, pero el USUARIO vendedor no podrá disponer de esos fondos hasta tanto cambie el estado de dicha operación en el SISTEMA a “Operación Completada”<br>
15.- La responsabilidad por las instrucciones de pago y sus consecuencias corresponde al  USUARIO.<br>
16.- Las constancias que arroja el SISTEMA constituyen prueba suficiente del cumplimiento íntegro de las instrucciones de pago, sustituyen a la necesidad de cualquier recibo y son plenamente oponibles aún en defecto de otras constancias emanadas del USUARIO en su calidad de vendedor o de terceros.<br> 
17.- No hay un monto mínimo ni máximo para las sumas acreditadas en la cuenta Dinero Mail por ventas de bienes y/o servicios. No obstante, podrá realizar ventas usando el SISTEMA, hasta por USD $1,200.00 (un mil doscientos dólares, moneda del curso legal en los Estados Unidos de América)  que previa autorización expresa de la EMPRESA podría aumentar el monto por transacción dependiendo el giro de la empresa y los productos que maneje, las operaciones realizadas por ventas superiores a esa cantidad son rechazadas automáticamente. La EMPRESA se reserva la facultad de verificar los datos registrados por el USUARIO comprador en el SISTEMA contra una Tarjeta de Crédito, cuenta bancaria, comprobante de aceptación de cargo, herramienta de prevención de fraude y/o recibo de pago de la tienda de conveniencia, depósito bancario en ventanilla o en línea.</p>
<br />
<h2 class="apriv">De la Jurisdicción y Ley Aplicable</h2>
<p class="apriv">Este acuerdo estará regido en todos sus puntos por las leyes vigentes en la República Mexicana, en particular respecto de mensajes de datos, contratación electrónica y comercio electrónico se regirá por lo dispuesto por la legislación federal respectiva. Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretación, alcance o cumplimiento, será sometida a las leyes aplicables y a los Tribunales competentes.<br>
Para la interpretación, cumplimiento y ejecución del presente contrato, las partes expresamente se someten a la jurisdicción de los tribunales competentes de la Ciudad de México, Distrito Federal, renunciando en consecuencia a cualquier fuero que en razón de su domicilio presente o futuro pudiera corresponderles<br>
El uso de este sitio web implica la aceptación de los Términos y Condiciones y del Aviso de Privacidad de Plaza de la Tecnología.<br>
Fecha de la última actualización.<br>
Estimado usuario, se le notifica que el Aviso de Privacidad ha sido modificado el día 13 de marzo de 2014.<br>
</p>
<br />
</section>